insert into user values (3331, sysdate(), 'adam@gmail.coz', 'Adam');
insert into user values (3332, sysdate(), 'eve@gmail.coz', 'Eve');
insert into user values (3333, sysdate(), 'jona@gmail.coz', 'Jonathan');
insert into user values (3334, sysdate(), 'ramez@gmail.cox', 'Ramez');
insert into user values (3335, sysdate(), 'helga@gmail.cox', 'Helga');
insert into user values (3341, sysdate(), 'goliah@gmail.cox', 'Goliah');
insert into user values (3342, sysdate(), 'loki@gmail.cox', 'Loki');
insert into user values (3343, sysdate(), 'thor@gmail.cox', 'Thor');
insert into user values (3344, sysdate(), 'remuel@gmail.cox', 'Remuel');
insert into user values (3345, sysdate(), 'ritah@gmail.cox', 'Ritah');
insert into user values (3346, sysdate(), 'anelka@gmail.cox', 'Anelka');
insert into user values (3347, sysdate(), 'anika@gmail.cox', 'Anika');
insert into user values (3348, sysdate(), 'mazza@gmail.cox', 'Mazza');

insert into post values (4441, sysdate(), 'description one', TRUE, sysdate(), 'title1', 3331);
insert into post values (4442, sysdate(), 'description two', FALSE, NULL, 'title2', 3331);
insert into post values (4443, sysdate(), 'description three', TRUE, sysdate(), 'title', 3331);
insert into post values (4444, sysdate(), 'description four', TRUE, sysdate(), 'title', 3331);
insert into post values (4445, sysdate(), 'description five', TRUE, sysdate(), 'title', 3331);
insert into post values (4446, sysdate(), 'description six', TRUE, sysdate(), 'title', 3331);
insert into post values (4447, sysdate(), 'description seven', TRUE, sysdate(), 'title', 3332);
insert into post values (4448, sysdate(), 'description eight', TRUE, sysdate(), 'title', 3332);
insert into post values (4449, sysdate(), 'description nine', TRUE, sysdate(), 'title', 3332);
insert into post values (4450, sysdate(), 'description ten', TRUE, sysdate(), 'title', 3332);
insert into post values (4451, sysdate(), 'description eleven', FALSE, NULL, 'title', 3332);
insert into post values (4452, sysdate(), 'description twelve', TRUE, sysdate(), 'title', 3333);
insert into post values (4453, sysdate(), 'description thirteen', TRUE, sysdate(), 'title', 3333);
insert into post values (4454, sysdate(), 'description fourteen', TRUE, sysdate(), 'title', 3333);
insert into post values (4455, sysdate(), 'description fifteen', TRUE, sysdate(), 'title', 3333);
insert into post values (4456, sysdate(), 'description sixteen', TRUE, sysdate(), 'title', 3334);
insert into post values (4457, sysdate(), 'description seventeen', TRUE, sysdate(), 'title', 3334);
insert into post values (4458, sysdate(), 'description eighteen', TRUE, sysdate(), 'title', 3335);
insert into post values (4459, sysdate(), 'description nineteen', TRUE, sysdate(), 'title', 3346);
insert into post values (4460, sysdate(), 'description twenty', TRUE, sysdate(), 'title', 3347);

insert into comment values(5551, sysdate(), 'comment zumba', 4441, 3332);
insert into comment values(5552, sysdate(), 'comment moka', 4441, 3332);
insert into comment values(5553, sysdate(), 'comment tabla', 4441, 3332);
insert into comment values(5554, sysdate(), 'comment yen', 4441, 3332);
insert into comment values(5555, sysdate(), 'comment franc', 4441, 3332);
insert into comment values(5556, sysdate(), 'comment euro', 4441, 3332);
insert into comment values(5557, sysdate(), 'comment dollar', 4441, 3331);
insert into comment values(5558, sysdate(), 'comment cent', 4441, 3331);
insert into comment values(5559, sysdate(), 'comment million', 4441, 3331);
insert into comment values(5560, sysdate(), 'comment hundred', 4444, 3332);
insert into comment values(5561, sysdate(), 'comment ninety', 4444, 3332);
insert into comment values(5562, sysdate(), 'comment nineteen', 4444, 3342);
insert into comment values(5563, sysdate(), 'comment eighty', 4443, 3333);
insert into comment values(5564, sysdate(), 'comment eighteen', 4443, 3345);
